/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v11.0
processor: LPC845
package_id: LPC845M301JBD64
mcu_data: ksdk2_0
processor_version: 11.0.1
board: LPCXpresso845
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 9fe6f390-d46e-4bfd-ab54-d5805709c7dd
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'uart_cmsis_common'
- type_id: 'uart_cmsis_common_9cb8e302497aa696fdbb5a4fd622c2a8'
- global_USART_CMSIS_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'gpio_adapter_common'
- type_id: 'gpio_adapter_common_57579b9ac814fe26bf95df0a384c36b6'
- global_gpio_adapter_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"
#include "fsl_syscon.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * PINT initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'PINT'
- type: 'pint'
- mode: 'interrupt_mode'
- custom_name_enabled: 'false'
- type_id: 'pint_cf4a806bb2a6c1ffced58ae2ed7b43af'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'PINT'
- config_sets:
  - general:
    - interrupt_array:
      - 0:
        - interrupt_id: 'INT_0'
        - interrupt_selection: 'PINT.0'
        - interrupt_type: 'kPINT_PinIntEnableFallEdge'
        - callback_function: 'pint_interrupt_callback'
        - enable_callback: 'true'
        - interrupt:
          - IRQn: 'PIN_INT0_IRQn'
          - enable_priority: 'false'
          - priority: '0'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void PINT_WakeupInit(void) {

  SYSCON_AttachSignal(SYSCON, PINT_INT_0, kSYSCON_GpioPort0Pin4ToPintsel);
  /* PINT initiation  */
  PINT_Init(PINT_PERIPHERAL);
  /* PINT PINT.0 configuration */
  PINT_PinInterruptConfig(PINT_PERIPHERAL, PINT_INT_0, kPINT_PinIntEnableFallEdge, pint_interrupt_callback);
  /* Enable PINT PINT.0 callback */
  PINT_EnableCallbackByIndex(PINT_PERIPHERAL, PINT_INT_0);
}

/***********************************************************************************************************************
 * FACEID uart initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'FACE'
- type: 'lpc_miniusart'
- mode: 'interrupt'
- custom_name_enabled: 'true'
- type_id: 'lpc_miniusart_78c250a8cd7edc52679c826bef63c9a6'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'USART1'
- config_sets:
  - fsl_usart:
    - usartConfig:
      - clockSource: 'FunctionClock'
      - clockSourceFreq: 'BOARD_BootClockFRO18M'
      - baudRate_Bps: '115200'
      - syncMode: 'kUSART_SyncModeDisabled'
      - parityMode: 'kUSART_ParityDisabled'
      - stopBitCount: 'kUSART_OneStopBit'
      - bitCountPerChar: 'kUSART_8BitsPerChar'
      - loopback: 'false'
      - enableRx: 'true'
      - enableTx: 'true'
      - clockPolarity: 'kUSART_RxSampleOnFallingEdge'
      - enableContinuousSCLK: 'false'
      - enableHardwareFlowControl: 'false'
  - Interrupt_cfg:
    - interrupts: 'kUSART_RxReadyInterruptEnable'
    - interrupt_vectors:
      - enable_rx_tx_irq: 'true'
      - interrupt_rx_tx:
        - IRQn: 'USART1_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
static void FACEID_UartInit(void) {
	usart_config_t FACEID_config = {
	  .baudRate_Bps = 115200UL,
	  .syncMode = kUSART_SyncModeDisabled,
	  .parityMode = kUSART_ParityDisabled,
	  .stopBitCount = kUSART_OneStopBit,
	  .bitCountPerChar = kUSART_8BitsPerChar,
	  .loopback = false,
	  .enableRx = true,
	  .enableTx = true,
	  .clockPolarity = kUSART_RxSampleOnFallingEdge,
	  .enableContinuousSCLK = false,
	  .enableHardwareFlowControl = false
	};
  /* USART1 peripheral initialization */
  USART_Init(FACEID_PERIPHERAL, &FACEID_config, FACEID_CLOCK_SOURCE);
  USART_EnableInterrupts(FACEID_PERIPHERAL, kUSART_RxReadyInterruptEnable);
  /* Enable interrupt USART1_IRQn request in the NVIC. */
  EnableIRQ(FACEID_USART_IRQN);
}

/***********************************************************************************************************************
 * TIMER initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'TIMER'
- type: 'wkt'
- mode: 'general'
- custom_name_enabled: 'true'
- type_id: 'wkt_09c536f4a06ae2280f5c720498226fe2'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'WKT'
- config_sets:
  - fsl_wkt:
    - wkt_configuration:
      - clockSource: 'kWKT_DividedFROClockSource'
      - clockSourceFreq: 'BOARD_BootClockFRO18M'
      - timerValueStr: '1Hz'
      - startTimer: 'false'
    - wkt_config_ut: []
    - interrupt_vector:
      - enable_irq: 'true'
      - interrupt:
        - IRQn: 'WKT_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
wkt_config_t TIMER_config = {
  .clockSource = kWKT_DividedFROClockSource
};

static void TIMER_init(void) {
  /* WKT initialization */
  WKT_Init(TIMER_PERIPHERAL, &TIMER_config);
  /* Enable interrupt WKT_IRQn request in the NVIC. */
  EnableIRQ(TIMER_WKT_IRQN);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Initialize components */
  PINT_WakeupInit();
  FACEID_UartInit();
  TIMER_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
