/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_pint.h"
#include "fsl_usart.h"
#include "fsl_clock.h"
#include "fsl_wkt.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* BOARD_InitPeripherals defines for PINT */
/* Definition of peripheral ID */
#define PINT_PERIPHERAL ((PINT_Type *) PINT_BASE)
/* PINT interrupt vector ID (number). */
#define PINT_PINT_0_IRQN PIN_INT0_IRQn
/* Definition of PINT interrupt ID for interrupt 0  */
#define PINT_INT_0 kPINT_PinInt0
/* BOARD_InitPeripherals defines for USART1 */
/* Definition of peripheral ID */
#define FACEID_PERIPHERAL ((USART_Type *)USART1)
/* Definition of the clock source frequency */
#define FACEID_CLOCK_SOURCE CLOCK_GetMainClkFreq()
/* FACE interrupt vector ID (number). */
#define FACEID_USART_IRQN USART1_IRQn
/* FACE interrupt handler identifier. */
#define FACEID_USART_IRQHANDLER USART1_IRQHandler
/* Definition of peripheral ID */
#define TIMER_PERIPHERAL WKT
/* Definition of time interval in ticks. */
#define TIMER_TIME_INTERVAL 750000UL
/* TIMER interrupt vector ID (number). */
#define TIMER_WKT_IRQN WKT_IRQn
/* TIMER interrupt handler identifier. */
#define TIMER_WKT_IRQHANDLER WKT_IRQHandler

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
/* WKT configuration structure. */
extern wkt_config_t TIMER_config;

/***********************************************************************************************************************
 * Callback functions
 **********************************************************************************************************************/
/* INT_0 callback function for the PINT component */
extern void pint_interrupt_callback(pint_pin_int_t pintr, uint32_t pmatch_status);

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
