/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v11.0
processor: LPC845
package_id: LPC845M301JBD64
mcu_data: ksdk2_0
processor_version: 11.0.1
board: LPCXpresso845
pin_labels:
- {pin_num: '48', pin_signal: PIO0_0/ACMP_I1}
- {pin_num: '24', pin_signal: PIO1_15, label: 'D2/P3[44]/P1_15-BLUE'}
- {pin_num: '4', pin_signal: PIO0_12, label: 'D3/P3[45]/SW1/P0_12-RED-ISP'}
- {pin_num: '37', pin_signal: PIO1_17}
- {pin_num: '36', pin_signal: PIO1_16}
- {pin_num: '14', pin_signal: SWDIO/PIO0_2, label: 'U4[17]/P4[2]/TARGET_SWDIO'}
- {pin_num: '12', pin_signal: SWCLK/PIO0_3, label: 'U4[16]/P4[4]/TARGET_SWCLK'}
- {pin_num: '5', pin_signal: RESETN/PIO0_5, label: MCU_RESET, identifier: MCU_RESET}
- {pin_num: '6', pin_signal: PIO0_4/ADC_11, label: PIR_WAKEUP, identifier: PIR_WAKEUP}
- {pin_num: '1', pin_signal: PIO1_8/CAPT_YL, label: FACEID_UART_TXD, identifier: FACEID_UART_TXD}
- {pin_num: '3', pin_signal: PIO1_9/CAPT_YH, label: FACEID_UART_RXD, identifier: FACEID_UART_RXD}
- {pin_num: '16', pin_signal: PIO0_11/I2C0_SDA, label: 'P3[40]/J1[2]/P0_11-I2C0_SDA'}
- {pin_num: '17', pin_signal: PIO0_10/I2C0_SCL, label: 'P3[41]/J1[1]/P0_10-I2C0_SCL'}
- {pin_num: '20', pin_signal: PIO1_2/CAPT_X3, label: DCDC_PG, identifier: DCDC_PG}
- {pin_num: '27', pin_signal: PIO0_25, label: DEBUG_UART_TXD, identifier: DEBUG_UART_TXD}
- {pin_num: '28', pin_signal: PIO0_24, label: DEBUG_UART_RXD, identifier: DEBUG_UART_RXD}
- {pin_num: '29', pin_signal: PIO1_3/CAPT_X4, label: SYS_PWR_CTL, identifier: SYS_PWR_CTL}
- {pin_num: '32', pin_signal: PIO0_1/ACMP_I2/CLKIN}
- {pin_num: '45', pin_signal: PIO0_7/ADC_0}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_gpio.h"
#include "fsl_iocon.h"
#include "fsl_swm.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true', fullInit: 'true'}
- pin_list:
  - {pin_num: '5', peripheral: SYSCON, signal: RESETN, pin_signal: RESETN/PIO0_5, mode: pullUp, invert: disabled, hysteresis: enabled, opendrain: disabled, smode: bypass,
    clkdiv: div0}
  - {pin_num: '6', peripheral: GPIO, signal: 'PIO0, 4', pin_signal: PIO0_4/ADC_11, direction: INPUT, mode: pullUp, invert: disabled, hysteresis: enabled, opendrain: disabled,
    smode: bypass, clkdiv: div0}
  - {pin_num: '29', peripheral: GPIO, signal: 'PIO1, 3', pin_signal: PIO1_3/CAPT_X4, direction: OUTPUT, gpio_init_state: 'false', mode: pullUp, invert: disabled,
    hysteresis: enabled, opendrain: disabled, smode: bypass, clkdiv: div0}
  - {pin_num: '28', peripheral: USART0, signal: RXD, pin_signal: PIO0_24, mode: pullUp, invert: disabled, hysteresis: enabled, opendrain: disabled, smode: bypass,
    clkdiv: div0}
  - {pin_num: '27', peripheral: USART0, signal: TXD, pin_signal: PIO0_25, mode: pullUp, invert: disabled, hysteresis: enabled, opendrain: disabled, smode: bypass,
    clkdiv: div0}
  - {pin_num: '3', peripheral: USART1, signal: RXD, pin_signal: PIO1_9/CAPT_YH, mode: pullUp, invert: disabled, hysteresis: enabled, opendrain: disabled, smode: bypass,
    clkdiv: div0}
  - {pin_num: '1', peripheral: USART1, signal: TXD, pin_signal: PIO1_8/CAPT_YL, mode: pullUp, invert: disabled, hysteresis: enabled, opendrain: disabled, smode: bypass,
    clkdiv: div0}
  - {pin_num: '6', peripheral: PINT, signal: 'PINT, 0', pin_signal: PIO0_4/ADC_11, identifier: '', mode: pullUp, invert: disabled, hysteresis: enabled, opendrain: disabled,
    smode: bypass, clkdiv: div0}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M0P */
void BOARD_InitPins(void)
{
    /* Enables clock for IOCON.: enable */
    CLOCK_EnableClock(kCLOCK_Iocon);
    /* Enables clock for switch matrix.: enable */
    CLOCK_EnableClock(kCLOCK_Swm);
    /* Enables the clock for the GPIO0 module */
    CLOCK_EnableClock(kCLOCK_Gpio0);
    /* Enables the clock for the GPIO1 module */
    CLOCK_EnableClock(kCLOCK_Gpio1);

    gpio_pin_config_t PIR_WAKEUP_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_4 (pin 6)  */
    GPIO_PinInit(BOARD_INITPINS_PIR_WAKEUP_GPIO, BOARD_INITPINS_PIR_WAKEUP_PORT, BOARD_INITPINS_PIR_WAKEUP_PIN, &PIR_WAKEUP_config);

    gpio_pin_config_t SYS_PWR_CTL_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO1_3 (pin 29)  */
    GPIO_PinInit(BOARD_INITPINS_SYS_PWR_CTL_GPIO, BOARD_INITPINS_SYS_PWR_CTL_PORT, BOARD_INITPINS_SYS_PWR_CTL_PIN, &SYS_PWR_CTL_config);

    gpio_pin_config_t DCDC_PG_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO1_2 (pin 20)  */
    GPIO_PinInit(BOARD_DCDC_PG_GPIO, BOARD_DCDC_PG_PORT, BOARD_DCDC_PG_PIN, &DCDC_PG_config);

    const uint32_t DEBUG_UART_RXD = (/* Selects pull-up function */
                                     IOCON_PIO_MODE_PULLUP |
                                     /* Enable hysteresis */
                                     IOCON_PIO_HYS_EN |
                                     /* Input not invert */
                                     IOCON_PIO_INV_DI |
                                     /* Disables Open-drain function */
                                     IOCON_PIO_OD_DI |
                                     /* Bypass input filter */
                                     IOCON_PIO_SMODE_BYPASS |
                                     /* IOCONCLKDIV0 */
                                     IOCON_PIO_CLKDIV0);
    /* PIO0 PIN24 (coords: 28) is configured as USART0, RXD. */
    IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_24, DEBUG_UART_RXD);

    const uint32_t DEBUG_UART_TXD = (/* Selects pull-up function */
                                     IOCON_PIO_MODE_PULLUP |
                                     /* Enable hysteresis */
                                     IOCON_PIO_HYS_EN |
                                     /* Input not invert */
                                     IOCON_PIO_INV_DI |
                                     /* Disables Open-drain function */
                                     IOCON_PIO_OD_DI |
                                     /* Bypass input filter */
                                     IOCON_PIO_SMODE_BYPASS |
                                     /* IOCONCLKDIV0 */
                                     IOCON_PIO_CLKDIV0);
    /* PIO0 PIN25 (coords: 27) is configured as USART0, TXD. */
    IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_25, DEBUG_UART_TXD);

//    const uint32_t PIR_WAKEUP = (/* Selects pull-up function */
//                                 IOCON_PIO_MODE_PULLUP |
//                                 /* Enable hysteresis */
//                                 IOCON_PIO_HYS_EN |
//                                 /* Input not invert */
//                                 IOCON_PIO_INV_DI |
//                                 /* Disables Open-drain function */
//                                 IOCON_PIO_OD_DI |
//                                 /* Bypass input filter */
//                                 IOCON_PIO_SMODE_BYPASS |
//                                 /* IOCONCLKDIV0 */
//                                 IOCON_PIO_CLKDIV0);
//    /* PIO0 PIN4 (coords: 6) is configured as GPIO, PIO0, 4. */
//    IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_4, PIR_WAKEUP);

    const uint32_t MCU_RESET = (/* Selects pull-up function */
                                IOCON_PIO_MODE_PULLUP |
                                /* Enable hysteresis */
                                IOCON_PIO_HYS_EN |
                                /* Input not invert */
                                IOCON_PIO_INV_DI |
                                /* Disables Open-drain function */
                                IOCON_PIO_OD_DI |
                                /* Bypass input filter */
                                IOCON_PIO_SMODE_BYPASS |
                                /* IOCONCLKDIV0 */
                                IOCON_PIO_CLKDIV0);
    /* PIO0 PIN5 (coords: 5) is configured as SYSCON, RESETN. */
    IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_5, MCU_RESET);

    const uint32_t SYS_PWR_CTL = (/* Selects pull-up function */
                                  IOCON_PIO_MODE_PULLUP |
                                  /* Enable hysteresis */
                                  IOCON_PIO_HYS_EN |
                                  /* Input not invert */
                                  IOCON_PIO_INV_DI |
                                  /* Disables Open-drain function */
                                  IOCON_PIO_OD_DI |
                                  /* Bypass input filter */
                                  IOCON_PIO_SMODE_BYPASS |
                                  /* IOCONCLKDIV0 */
                                  IOCON_PIO_CLKDIV0);
    /* PIO1 PIN3 (coords: 29) is configured as GPIO, PIO1, 3. */
    IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO1_3, SYS_PWR_CTL);

    const uint32_t DCDC_PG = (/* Enable hysteresis */
                              IOCON_PIO_HYS_EN |
                              /* Input not invert */
                              IOCON_PIO_INV_DI |
                              /* Disables Open-drain function */
                              IOCON_PIO_OD_DI |
                              /* Bypass input filter */
                              IOCON_PIO_SMODE_BYPASS |
                              /* IOCONCLKDIV0 */
                              IOCON_PIO_CLKDIV0);
    /* PIO1 PIN3 (coords: 20) is configured as GPIO, PIO1, 3. */
    IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO1_2, DCDC_PG);

    const uint32_t FACEID_UART_TXD = (/* Selects pull-up function */
                                    IOCON_PIO_MODE_PULLUP |
                                    /* Enable hysteresis */
                                    IOCON_PIO_HYS_EN |
                                    /* Input not invert */
                                    IOCON_PIO_INV_DI |
                                    /* Disables Open-drain function */
                                    IOCON_PIO_OD_DI |
                                    /* Bypass input filter */
                                    IOCON_PIO_SMODE_BYPASS |
                                    /* IOCONCLKDIV0 */
                                    IOCON_PIO_CLKDIV0);
    /* PIO1 PIN8 (coords: 1) is configured as USART1, TXD. */
    IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO1_8, FACEID_UART_TXD);

    const uint32_t FACEID_UART_RXD = (/* Selects pull-up function */
                                    IOCON_PIO_MODE_PULLUP |
                                    /* Enable hysteresis */
                                    IOCON_PIO_HYS_EN |
                                    /* Input not invert */
                                    IOCON_PIO_INV_DI |
                                    /* Disables Open-drain function */
                                    IOCON_PIO_OD_DI |
                                    /* Bypass input filter */
                                    IOCON_PIO_SMODE_BYPASS |
                                    /* IOCONCLKDIV0 */
                                    IOCON_PIO_CLKDIV0);
    /* PIO1 PIN9 (coords: 3) is configured as USART1, RXD. */
    IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO1_9, FACEID_UART_RXD);

    /* USART0_TXD connect to P0_25 */
    SWM_SetMovablePinSelect(SWM0, kSWM_USART0_TXD, kSWM_PortPin_P0_25);

    /* USART0_RXD connect to P0_24 */
    SWM_SetMovablePinSelect(SWM0, kSWM_USART0_RXD, kSWM_PortPin_P0_24);

    /* USART1_TXD connect to P1_8 */
    SWM_SetMovablePinSelect(SWM0, kSWM_USART1_TXD, kSWM_PortPin_P1_8);

    /* USART1_RXD connect to P1_9 */
    SWM_SetMovablePinSelect(SWM0, kSWM_USART1_RXD, kSWM_PortPin_P1_9);

    /* RESETN connect to P0_5 */
    SWM_SetFixedPinSelect(SWM0, kSWM_RESETN, true);

    SYSCON->PINTSEL[0] = ((SYSCON->PINTSEL[0] &
                           /* Mask bits to zero which are setting */
                           (~(SYSCON_PINTSEL_INTPIN_MASK)))

                          /* Pin number select for pin interrupt or pattern match engine input. (PIO0_0 to
                           * PIO0_31correspond to numbers 0 to 31 and PIO1_0 to PIO1_31 correspond to numbers 32 to
                           * 63).: 0x04u */
                          | SYSCON_PINTSEL_INTPIN(0x04u));

    /* I2C0_SDA connect to P0_11 */
    SWM_SetFixedPinSelect(SWM0, kSWM_I2C0_SDA, true);

    /* I2C0_SCL connect to P0_10 */
    SWM_SetFixedPinSelect(SWM0, kSWM_I2C0_SCL, true);

    /* Disable clock for switch matrix. */
    CLOCK_DisableClock(kCLOCK_Swm);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
